//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVerktygProjektOlofBuhlin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public int QuizId { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }
        public int StudentStudentId { get; set; }
        public int TeacherTeacherId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
