//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVerktygProjektOlofBuhlin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestVerktygContext : DbContext
    {
        public TestVerktygContext()
            : base("name=TestVerktygContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Quiz> QuizSet { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
